---
metal_project_id: "{{ lookup('env', 'METAL_PROJ_ID') }}"
metal_facility: da11
metal_metro: da

metal_opsbox_config: "m3.small.x86"
metal_ocp_control_host_config: "m3.small.x86"
metal_ocp_num_control_hosts: 3
metal_ocp_worker_host_config: "m3.small.x86"
metal_ocp_num_worker_hosts: 1
metal_ip_block_size: 16
